apiVersion: v1
kind: Namespace
metadata:
  name: envsubst-demo

---

apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: envsubst-demo
type: Opaque
stringData:
  USERNAME: "myuser"
  PASSWORD: "mysecret"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
  namespace: envsubst-demo
data:
  app.conf.template: |
    username = ${USERNAME}
    password = ${PASSWORD}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: envsubst-demo
  namespace: envsubst-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envsubst-demo
  template:
    metadata:
      labels:
        app: envsubst-demo
    spec:
      containers:
        - name: demo-container
          image: alpine:latest
          command:
            - sh
            - -c
            - |
              apk add --no-cache gettext
              envsubst < /config/app.conf.template > /output/app.conf
              echo "Resolved file:"
              cat /output/app.conf
              sleep 3600  # Keep container running for testing
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: PASSWORD
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: output-volume
              mountPath: /output
      volumes:
        - name: config-volume
          configMap:
            name: demo-configmap
        - name: output-volume
          emptyDir: {}